### ISSUE TITLE
Show error message if wallet is empty

### ISSUE THREAD

**Issue by MBeuttler** [IUNO-TDM/MixerControl#112]
The order process gets stuck in case of an empty wallet.

This happens especially when deploying a new mixer environment from scratch and then trying to pay via wallet app.

In this case the order process stops at "waiting for license"

**Comment by bockha** [comment]
The order process is not stuck completely but blocks until the pending transaction is mined into a block.

The machine **owner** shall be notified to fund the machines wallet with some change while it is empty.
