### ISSUE TITLE
start button workflow

### ISSUE THREAD

**Issue by bockha** [IUNO-TDM/MixerControl#117]
The workflow to start the production of a drink shall be changed according to these steps:
1. Lighten or flash the start button of the machine to signal its control is ready to mix the licensed drink recipe.
2. Wait until the start button is pressed.
3. Unlighten the start button.
4. Start mixing the licensed drink recipe.

The start button is wired to [~~GPIO04~~ GPIO23](http://raspberrypi.ws/pin16) on the new [MotorShield](https://github.com/IUNO-TDM/MotorShield/tree/V01.00.00).

![MotorShield](https://user-images.githubusercontent.com/24431070/34865941-f5d7e4ec-f77a-11e7-81e5-0a1f2d41100e.png)

**Comment by goergch** [comment]
halfway done. When PumpControl implements the feature, it can be tested
