### ISSUE TITLE
mixer control takes too much iunos

### ISSUE THREAD

**Issue by bockha** [IUNO-TDM/MixerControl#119]
The invoice displayed by mixer control shows an total amount of 2 IUNO, but [in reality it takes 4 IUNO](https://www.blocktrail.com/tBTC/tx/8ac918d1477edf80d39a2d5332b873fb941ee39f5161e674f01869886cb7fd99).

![img_20180119_073810042](https://user-images.githubusercontent.com/24431070/35137976-0865104e-fce4-11e7-8c5e-914829af59e2.jpg)

![invoice](https://user-images.githubusercontent.com/24431070/35137956-f4c038b6-fce3-11e7-9040-c632fcdba0f4.PNG)

**Comment by goergch** [comment]
fixed in 37a231c0dd327a8758b8c47ff0e8f6dc548433dc
