### ISSUE TITLE
create a Raspi Image

### ISSUE THREAD

**Issue by goergch** [IUNO-TDM/MixerControl#22]

**Comment by hpbock** [comment]
this is necessary not before there are more than a handful of machines at different project partners

**Comment by bockha** [comment]
The image shall have the overlay ```spi1-cs2``` enabled for supporting [MotorShield V01.00.00](https://github.com/IUNO-TDM/MotorShield/releases/tag/V01.00.00).

**Comment by MBeuttler** [comment]
![f9611f48-fd1a-48a3-b894-749e61b4b6c3](https://user-images.githubusercontent.com/3037112/35724406-e3014712-07fd-11e8-9e23-79b044f8621e.png)

**Comment by goergch** [comment]
fixed in mixerinstallation repo
