### ISSUE TITLE
define and develop graphs for dashboards

### ISSUE THREAD

**Issue by hpbock** [IUNO-TDM/MixerControl#24]
1. collect ideas down in the comments about possible graphs and diagrams to be used in a dashboard of one mixing machine
2. implement selected graphs and diagrams for a dashboard during the intech 2017

**Comment by hpbock** [comment]
some ideas
- amount of mixed drinks during the last few hours
- top ten drinks of today
- top ten drinks ever
- amount of todays consumed juices

**Comment by goergch** [comment]
datasources:

- amount of mixed drinks during the last few hours (activated licenses)
- top ten drinks of today (activated licenses)
- top ten drinks ever  (activated licenses)
- favorite juices ( (activated licenses * metadata) / favorite tags
- histogram about workload over the day (activated licenses)
- revenue per day and machine owner, marketplace and license fees (payments / Transactions)
-
