### ISSUE TITLE
caching vs. connection keep alive

### ISSUE THREAD

**Issue by bockha** [IUNO-TDM/MixerControl#51]
The explicit caching of all rest routes without static content shall be reset to standard behaviour.
To deal with the performance problem of the raspberry pi with the handshake of SSl connections, Nginx shall be configured to allow [connection keep alive](https://www.nginx.com/blog/tuning-nginx/).

**Comment by MBeuttler** [comment]
1. What is "standard behaviour"?
2. Caching is not enabled for any REST Route. Only static HTML Content is cached via Cache-Control
3. Connection Keep Alive is already enabled.
