### ISSUE TITLE
MixerControl is blocking

### ISSUE THREAD

**Issue by goergch** [IUNO-TDM/MixerControl#58]
The MixerControl blocks sporadically completely. There is no obvious reason. After 10-15 minutes the system heals itself.

Sometimes the error occurred, when the service mode at the PumpControl was activated

**Comment by bockha** [comment]
Did it just disappear during refactoring or was there a bug that you could fix?

**Comment by MBeuttler** [comment]
We had alot of refactoring and haven't seen this behaviour again. My guess is, that it was fixed during refactoring. Let's wait and see how the MixerControl works on the EMO and may reopen this issue again.
