### ISSUE TITLE
Optimize coupon redemption

### ISSUE THREAD

**Issue by goergch** [IUNO-TDM/MixerControl#60]
- [x] display the coupon credit before and after redemption
- [x] allow multiple coupons for paying a drink

**Comment by bockha** [comment]
The redeemed coupon  value shall be shown in the invoice. The completed invoice shall be shown during the whole licensing process.

**Comment by bockha** [comment]
done, see this [tx](https://testnet.smartbit.com.au/tx/16b54643b634b1d60311f58b509ef70be934e01ec1599c0bb0ae1109c86f9031)
