### ISSUE TITLE
Broadcast iBeacon on Raspberry Pi

### ISSUE THREAD

**Issue by goergch** [IUNO-TDM/MixerControl#95]
The iOS Wallet Coupon reacts on the proximity UUID 1E809A70-DF5E-4C81-BFE0-549D552D0BAF. The raspberry pi should broadcast the iBeacon signal with the matching uuid

**Comment by bockha** [comment]
https://webgazer.org/update/tutorial/2016/03/16/raspberrypi-eddystone-url.html

**Comment by goergch** [comment]
Gibt es Software die Eddystone und iBeacon zeitlich multiplexed? Eddystone allein bringt mir leider nichts

**Comment by bockha** [comment]
@goergch ja, bash, python, perl, ...
Wie ist der Shell-Aufruf der wo den Raspberry Pi ein iBeacon senden läßt?

**Comment by goergch** [comment]
start beacon:

#!/bin/sh
sudo hciconfig hci0 up
sudo hciconfig hci0 leadv 3
sudo hciconfig hci0 noscan
sudo hcitool -i hci0 cmd 0x08 0x0008 1E 02 01 1A 1A FF 4C 00 02 15 1E 80 9A 70 DF 5E 4C 81 BF E0 54 9D 55 2D 0B AF 00 00 00 00 C8


stop beacon

#!/bin/sh
sudo hciconfig hci0 noleadv

**Comment by bockha** [comment]
Your [commands](http://yencarnacion.github.io/eddystone-url-calculator/) for "https://iuno.axoom.cloud" are:
```
$ sudo hciconfig hci0 up

$ sudo hciconfig hci0 leadv 3

$ sudo hcitool -i hci0 cmd 0x08 0x0008 1e 02 01 06 03 03 aa fe 16 16 aa fe 10 00 03 69 75 6e 6f 2e 61 78 6f 6f 6d 2e 63 6c 6f 75 64 00
```
